// Auto-generated by the Supabase CLI (generate_typescript_types) from the live
// project schema. Do not hand-edit — regenerate after any migration change.
// See AGENTS.md Rule 3 (this file is exempt from the 100-line guideline) and
// Rule 8 (all domain types in features/*/types.ts derive from this file).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      admin_roles: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: Database["public"]["Enums"]["admin_role_name"]
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: Database["public"]["Enums"]["admin_role_name"]
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: Database["public"]["Enums"]["admin_role_name"]
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          action: Database["public"]["Enums"]["audit_action"]
          actor_id: string | null
          created_at: string
          diff: Json | null
          entity_id: string | null
          entity_type: Database["public"]["Enums"]["entity_type"] | null
          id: string
          notes: string | null
        }
        Insert: {
          action: Database["public"]["Enums"]["audit_action"]
          actor_id?: string | null
          created_at?: string
          diff?: Json | null
          entity_id?: string | null
          entity_type?: Database["public"]["Enums"]["entity_type"] | null
          id?: string
          notes?: string | null
        }
        Update: {
          action?: Database["public"]["Enums"]["audit_action"]
          actor_id?: string | null
          created_at?: string
          diff?: Json | null
          entity_id?: string | null
          entity_type?: Database["public"]["Enums"]["entity_type"] | null
          id?: string
          notes?: string | null
        }
        Relationships: []
      }
      constituencies: {
        Row: {
          constituency_type: Database["public"]["Enums"]["constituency_type"]
          created_at: string
          delimitation_year: number | null
          district_id: string | null
          id: string
          name: string
          number: number | null
          reserved_category: Database["public"]["Enums"]["reservation_category"]
          slug: string
          state_id: string | null
          status: Database["public"]["Enums"]["geography_status"]
          total_electors: number | null
          union_territory_id: string | null
          updated_at: string
        }
        Insert: {
          constituency_type: Database["public"]["Enums"]["constituency_type"]
          created_at?: string
          delimitation_year?: number | null
          district_id?: string | null
          id?: string
          name: string
          number?: number | null
          reserved_category?: Database["public"]["Enums"]["reservation_category"]
          slug: string
          state_id?: string | null
          status?: Database["public"]["Enums"]["geography_status"]
          total_electors?: number | null
          union_territory_id?: string | null
          updated_at?: string
        }
        Update: {
          constituency_type?: Database["public"]["Enums"]["constituency_type"]
          created_at?: string
          delimitation_year?: number | null
          district_id?: string | null
          id?: string
          name?: string
          number?: number | null
          reserved_category?: Database["public"]["Enums"]["reservation_category"]
          slug?: string
          state_id?: string | null
          status?: Database["public"]["Enums"]["geography_status"]
          total_electors?: number | null
          union_territory_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "constituencies_district_id_fkey"
            columns: ["district_id"]
            isOneToOne: false
            referencedRelation: "districts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "constituencies_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "constituencies_union_territory_id_fkey"
            columns: ["union_territory_id"]
            isOneToOne: false
            referencedRelation: "union_territories"
            referencedColumns: ["id"]
          },
        ]
      }
      corrections: {
        Row: {
          created_at: string
          current_value: string | null
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          field_name: string | null
          id: string
          reason: string
          review_notes: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["correction_status"]
          submitter_email: string | null
          submitter_name: string | null
          suggested_value: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          current_value?: string | null
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          field_name?: string | null
          id?: string
          reason: string
          review_notes?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["correction_status"]
          submitter_email?: string | null
          submitter_name?: string | null
          suggested_value: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          current_value?: string | null
          entity_id?: string
          entity_type?: Database["public"]["Enums"]["entity_type"]
          field_name?: string | null
          id?: string
          reason?: string
          review_notes?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["correction_status"]
          submitter_email?: string | null
          submitter_name?: string | null
          suggested_value?: string
          updated_at?: string
        }
        Relationships: []
      }
      data_import_records: {
        Row: {
          created_at: string
          data_import_id: string
          entity_id: string | null
          entity_type: Database["public"]["Enums"]["entity_type"] | null
          error_message: string | null
          id: string
          match_status: Database["public"]["Enums"]["import_match_status"]
          raw_data: Json | null
        }
        Insert: {
          created_at?: string
          data_import_id: string
          entity_id?: string | null
          entity_type?: Database["public"]["Enums"]["entity_type"] | null
          error_message?: string | null
          id?: string
          match_status?: Database["public"]["Enums"]["import_match_status"]
          raw_data?: Json | null
        }
        Update: {
          created_at?: string
          data_import_id?: string
          entity_id?: string | null
          entity_type?: Database["public"]["Enums"]["entity_type"] | null
          error_message?: string | null
          id?: string
          match_status?: Database["public"]["Enums"]["import_match_status"]
          raw_data?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "data_import_records_data_import_id_fkey"
            columns: ["data_import_id"]
            isOneToOne: false
            referencedRelation: "data_imports"
            referencedColumns: ["id"]
          },
        ]
      }
      data_imports: {
        Row: {
          completed_at: string | null
          created_at: string
          data_source_id: string
          error_summary: string | null
          id: string
          initiated_by: string | null
          records_created: number
          records_failed: number
          records_processed: number
          records_updated: number
          started_at: string | null
          status: Database["public"]["Enums"]["import_status"]
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          data_source_id: string
          error_summary?: string | null
          id?: string
          initiated_by?: string | null
          records_created?: number
          records_failed?: number
          records_processed?: number
          records_updated?: number
          started_at?: string | null
          status?: Database["public"]["Enums"]["import_status"]
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          data_source_id?: string
          error_summary?: string | null
          id?: string
          initiated_by?: string | null
          records_created?: number
          records_failed?: number
          records_processed?: number
          records_updated?: number
          started_at?: string | null
          status?: Database["public"]["Enums"]["import_status"]
        }
        Relationships: [
          {
            foreignKeyName: "data_imports_data_source_id_fkey"
            columns: ["data_source_id"]
            isOneToOne: false
            referencedRelation: "data_sources"
            referencedColumns: ["id"]
          },
        ]
      }
      data_quality_issues: {
        Row: {
          created_at: string
          description: string | null
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          id: string
          is_resolved: boolean
          issue_type: Database["public"]["Enums"]["data_quality_issue_type"]
          resolved_at: string | null
          resolved_by: string | null
          severity: Database["public"]["Enums"]["data_quality_severity"]
        }
        Insert: {
          created_at?: string
          description?: string | null
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          id?: string
          is_resolved?: boolean
          issue_type: Database["public"]["Enums"]["data_quality_issue_type"]
          resolved_at?: string | null
          resolved_by?: string | null
          severity?: Database["public"]["Enums"]["data_quality_severity"]
        }
        Update: {
          created_at?: string
          description?: string | null
          entity_id?: string
          entity_type?: Database["public"]["Enums"]["entity_type"]
          id?: string
          is_resolved?: boolean
          issue_type?: Database["public"]["Enums"]["data_quality_issue_type"]
          resolved_at?: string | null
          resolved_by?: string | null
          severity?: Database["public"]["Enums"]["data_quality_severity"]
        }
        Relationships: []
      }
      data_sources: {
        Row: {
          created_at: string
          id: string
          ingestion_method: string | null
          is_active: boolean
          last_run_at: string | null
          name: string
          schedule_cron: string | null
          source_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          ingestion_method?: string | null
          is_active?: boolean
          last_run_at?: string | null
          name: string
          schedule_cron?: string | null
          source_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          ingestion_method?: string | null
          is_active?: boolean
          last_run_at?: string | null
          name?: string
          schedule_cron?: string | null
          source_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "data_sources_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      districts: {
        Row: {
          created_at: string
          formation_date: string | null
          headquarters: string | null
          id: string
          name: string
          state_id: string | null
          status: Database["public"]["Enums"]["geography_status"]
          union_territory_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          formation_date?: string | null
          headquarters?: string | null
          id?: string
          name: string
          state_id?: string | null
          status?: Database["public"]["Enums"]["geography_status"]
          union_territory_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          formation_date?: string | null
          headquarters?: string | null
          id?: string
          name?: string
          state_id?: string | null
          status?: Database["public"]["Enums"]["geography_status"]
          union_territory_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "districts_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "districts_union_territory_id_fkey"
            columns: ["union_territory_id"]
            isOneToOne: false
            referencedRelation: "union_territories"
            referencedColumns: ["id"]
          },
        ]
      }
      documents: {
        Row: {
          created_at: string
          description: string | null
          document_type: Database["public"]["Enums"]["document_type"]
          file_url: string | null
          id: string
          published_date: string | null
          source_record_id: string | null
          storage_path: string | null
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          document_type: Database["public"]["Enums"]["document_type"]
          file_url?: string | null
          id?: string
          published_date?: string | null
          source_record_id?: string | null
          storage_path?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          document_type?: Database["public"]["Enums"]["document_type"]
          file_url?: string | null
          id?: string
          published_date?: string | null
          source_record_id?: string | null
          storage_path?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_source_record_id_fkey"
            columns: ["source_record_id"]
            isOneToOne: false
            referencedRelation: "source_records"
            referencedColumns: ["id"]
          },
        ]
      }
      election_candidates: {
        Row: {
          age_at_nomination: number | null
          candidate_name: string
          constituency_id: string
          created_at: string
          criminal_cases_declared: number | null
          declared_assets: number | null
          deposit_status: Database["public"]["Enums"]["deposit_status"] | null
          education_declared: string | null
          election_id: string
          id: string
          nomination_status: Database["public"]["Enums"]["candidate_nomination_status"]
          party_id: string | null
          politician_id: string | null
          result_status:
            | Database["public"]["Enums"]["candidate_result_status"]
            | null
          source_id: string | null
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        Insert: {
          age_at_nomination?: number | null
          candidate_name: string
          constituency_id: string
          created_at?: string
          criminal_cases_declared?: number | null
          declared_assets?: number | null
          deposit_status?: Database["public"]["Enums"]["deposit_status"] | null
          education_declared?: string | null
          election_id: string
          id?: string
          nomination_status?: Database["public"]["Enums"]["candidate_nomination_status"]
          party_id?: string | null
          politician_id?: string | null
          result_status?:
            | Database["public"]["Enums"]["candidate_result_status"]
            | null
          source_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Update: {
          age_at_nomination?: number | null
          candidate_name?: string
          constituency_id?: string
          created_at?: string
          criminal_cases_declared?: number | null
          declared_assets?: number | null
          deposit_status?: Database["public"]["Enums"]["deposit_status"] | null
          education_declared?: string | null
          election_id?: string
          id?: string
          nomination_status?: Database["public"]["Enums"]["candidate_nomination_status"]
          party_id?: string | null
          politician_id?: string | null
          result_status?:
            | Database["public"]["Enums"]["candidate_result_status"]
            | null
          source_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "election_candidates_constituency_id_fkey"
            columns: ["constituency_id"]
            isOneToOne: false
            referencedRelation: "constituencies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "election_candidates_election_id_fkey"
            columns: ["election_id"]
            isOneToOne: false
            referencedRelation: "elections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "election_candidates_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "election_candidates_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
          {
            foreignKeyName: "election_candidates_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_house_members"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "election_candidates_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "election_candidates_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_position_holders"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "election_candidates_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "politicians"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "election_candidates_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "public_politician_overview"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "election_candidates_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      election_results: {
        Row: {
          created_at: string
          election_candidate_id: string
          evm_votes: number | null
          id: string
          is_winner: boolean
          margin: number | null
          postal_votes: number | null
          rank: number | null
          source_id: string | null
          updated_at: string
          vote_share_percent: number | null
          votes_received: number
        }
        Insert: {
          created_at?: string
          election_candidate_id: string
          evm_votes?: number | null
          id?: string
          is_winner?: boolean
          margin?: number | null
          postal_votes?: number | null
          rank?: number | null
          source_id?: string | null
          updated_at?: string
          vote_share_percent?: number | null
          votes_received?: number
        }
        Update: {
          created_at?: string
          election_candidate_id?: string
          evm_votes?: number | null
          id?: string
          is_winner?: boolean
          margin?: number | null
          postal_votes?: number | null
          rank?: number | null
          source_id?: string | null
          updated_at?: string
          vote_share_percent?: number | null
          votes_received?: number
        }
        Relationships: [
          {
            foreignKeyName: "election_results_election_candidate_id_fkey"
            columns: ["election_candidate_id"]
            isOneToOne: true
            referencedRelation: "election_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "election_results_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      elections: {
        Row: {
          created_at: string
          election_type: Database["public"]["Enums"]["election_type"]
          end_date: string | null
          house_id: string | null
          id: string
          name: string
          phases: number | null
          slug: string
          source_id: string | null
          start_date: string | null
          state_id: string | null
          status: Database["public"]["Enums"]["election_status"]
          term_id: string | null
          total_seats: number | null
          union_territory_id: string | null
          updated_at: string
          voter_turnout_percent: number | null
        }
        Insert: {
          created_at?: string
          election_type: Database["public"]["Enums"]["election_type"]
          end_date?: string | null
          house_id?: string | null
          id?: string
          name: string
          phases?: number | null
          slug: string
          source_id?: string | null
          start_date?: string | null
          state_id?: string | null
          status?: Database["public"]["Enums"]["election_status"]
          term_id?: string | null
          total_seats?: number | null
          union_territory_id?: string | null
          updated_at?: string
          voter_turnout_percent?: number | null
        }
        Update: {
          created_at?: string
          election_type?: Database["public"]["Enums"]["election_type"]
          end_date?: string | null
          house_id?: string | null
          id?: string
          name?: string
          phases?: number | null
          slug?: string
          source_id?: string | null
          start_date?: string | null
          state_id?: string | null
          status?: Database["public"]["Enums"]["election_status"]
          term_id?: string | null
          total_seats?: number | null
          union_territory_id?: string | null
          updated_at?: string
          voter_turnout_percent?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "elections_house_id_fkey"
            columns: ["house_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "elections_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "elections_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "elections_term_id_fkey"
            columns: ["term_id"]
            isOneToOne: false
            referencedRelation: "parliamentary_terms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "elections_union_territory_id_fkey"
            columns: ["union_territory_id"]
            isOneToOne: false
            referencedRelation: "union_territories"
            referencedColumns: ["id"]
          },
        ]
      }
      entity_documents: {
        Row: {
          created_at: string
          document_id: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          id: string
        }
        Insert: {
          created_at?: string
          document_id: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          id?: string
        }
        Update: {
          created_at?: string
          document_id?: string
          entity_id?: string
          entity_type?: Database["public"]["Enums"]["entity_type"]
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "entity_documents_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      entity_sources: {
        Row: {
          created_at: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          field_name: string | null
          id: string
          notes: string | null
          relationship: Database["public"]["Enums"]["entity_source_relationship"]
          source_record_id: string
        }
        Insert: {
          created_at?: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          field_name?: string | null
          id?: string
          notes?: string | null
          relationship?: Database["public"]["Enums"]["entity_source_relationship"]
          source_record_id: string
        }
        Update: {
          created_at?: string
          entity_id?: string
          entity_type?: Database["public"]["Enums"]["entity_type"]
          field_name?: string | null
          id?: string
          notes?: string | null
          relationship?: Database["public"]["Enums"]["entity_source_relationship"]
          source_record_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "entity_sources_source_record_id_fkey"
            columns: ["source_record_id"]
            isOneToOne: false
            referencedRelation: "source_records"
            referencedColumns: ["id"]
          },
        ]
      }
      government_parties: {
        Row: {
          created_at: string
          effective_from: string
          effective_to: string | null
          government_id: string
          id: string
          party_id: string
          role: Database["public"]["Enums"]["government_party_role"]
          seats_contributed: number | null
        }
        Insert: {
          created_at?: string
          effective_from: string
          effective_to?: string | null
          government_id: string
          id?: string
          party_id: string
          role?: Database["public"]["Enums"]["government_party_role"]
          seats_contributed?: number | null
        }
        Update: {
          created_at?: string
          effective_from?: string
          effective_to?: string | null
          government_id?: string
          id?: string
          party_id?: string
          role?: Database["public"]["Enums"]["government_party_role"]
          seats_contributed?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "government_parties_government_id_fkey"
            columns: ["government_id"]
            isOneToOne: false
            referencedRelation: "governments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "government_parties_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "government_parties_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
        ]
      }
      governments: {
        Row: {
          created_at: string
          dissolved_date: string | null
          formed_date: string
          id: string
          level: Database["public"]["Enums"]["government_level"]
          state_id: string | null
          status: Database["public"]["Enums"]["government_status"]
          term_number: number | null
          union_territory_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          dissolved_date?: string | null
          formed_date: string
          id?: string
          level: Database["public"]["Enums"]["government_level"]
          state_id?: string | null
          status?: Database["public"]["Enums"]["government_status"]
          term_number?: number | null
          union_territory_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          dissolved_date?: string | null
          formed_date?: string
          id?: string
          level?: Database["public"]["Enums"]["government_level"]
          state_id?: string | null
          status?: Database["public"]["Enums"]["government_status"]
          term_number?: number | null
          union_territory_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "governments_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "governments_union_territory_id_fkey"
            columns: ["union_territory_id"]
            isOneToOne: false
            referencedRelation: "union_territories"
            referencedColumns: ["id"]
          },
        ]
      }
      houses: {
        Row: {
          created_at: string
          house_type: Database["public"]["Enums"]["house_type"]
          id: string
          is_permanent: boolean
          name: string
          state_id: string | null
          total_seats: number | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          house_type: Database["public"]["Enums"]["house_type"]
          id?: string
          is_permanent?: boolean
          name: string
          state_id?: string | null
          total_seats?: number | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          house_type?: Database["public"]["Enums"]["house_type"]
          id?: string
          is_permanent?: boolean
          name?: string
          state_id?: string | null
          total_seats?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "houses_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
        ]
      }
      minister_assignments: {
        Row: {
          created_at: string
          effective_from: string
          effective_to: string | null
          government_id: string
          id: string
          is_primary: boolean
          ministry_id: string | null
          politician_id: string
          portfolio_id: string | null
          rank: Database["public"]["Enums"]["minister_rank"]
          source_id: string | null
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        Insert: {
          created_at?: string
          effective_from: string
          effective_to?: string | null
          government_id: string
          id?: string
          is_primary?: boolean
          ministry_id?: string | null
          politician_id: string
          portfolio_id?: string | null
          rank?: Database["public"]["Enums"]["minister_rank"]
          source_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Update: {
          created_at?: string
          effective_from?: string
          effective_to?: string | null
          government_id?: string
          id?: string
          is_primary?: boolean
          ministry_id?: string | null
          politician_id?: string
          portfolio_id?: string | null
          rank?: Database["public"]["Enums"]["minister_rank"]
          source_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "minister_assignments_government_id_fkey"
            columns: ["government_id"]
            isOneToOne: false
            referencedRelation: "governments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "minister_assignments_ministry_id_fkey"
            columns: ["ministry_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["ministry_id"]
          },
          {
            foreignKeyName: "minister_assignments_ministry_id_fkey"
            columns: ["ministry_id"]
            isOneToOne: false
            referencedRelation: "ministries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "minister_assignments_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_house_members"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "minister_assignments_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "minister_assignments_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_position_holders"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "minister_assignments_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "politicians"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "minister_assignments_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "public_politician_overview"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "minister_assignments_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["portfolio_id"]
          },
          {
            foreignKeyName: "minister_assignments_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "minister_assignments_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      ministries: {
        Row: {
          created_at: string
          id: string
          level: Database["public"]["Enums"]["government_level"]
          name: string
          state_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          level: Database["public"]["Enums"]["government_level"]
          name: string
          state_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          level?: Database["public"]["Enums"]["government_level"]
          name?: string
          state_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ministries_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
        ]
      }
      parliamentary_terms: {
        Row: {
          created_at: string
          end_date: string | null
          house_id: string
          id: string
          start_date: string | null
          term_number: number | null
        }
        Insert: {
          created_at?: string
          end_date?: string | null
          house_id: string
          id?: string
          start_date?: string | null
          term_number?: number | null
        }
        Update: {
          created_at?: string
          end_date?: string | null
          house_id?: string
          id?: string
          start_date?: string | null
          term_number?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "parliamentary_terms_house_id_fkey"
            columns: ["house_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id"]
          },
        ]
      }
      party_aliases: {
        Row: {
          alias: string
          alias_type: Database["public"]["Enums"]["party_alias_type"]
          created_at: string
          id: string
          party_id: string
        }
        Insert: {
          alias: string
          alias_type?: Database["public"]["Enums"]["party_alias_type"]
          created_at?: string
          id?: string
          party_id: string
        }
        Update: {
          alias?: string
          alias_type?: Database["public"]["Enums"]["party_alias_type"]
          created_at?: string
          id?: string
          party_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "party_aliases_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_aliases_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
        ]
      }
      party_memberships: {
        Row: {
          created_at: string
          effective_from: string
          effective_to: string | null
          id: string
          is_current: boolean
          membership_type: Database["public"]["Enums"]["party_membership_type"]
          office_title: string | null
          party_id: string
          politician_id: string
          source_id: string | null
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        Insert: {
          created_at?: string
          effective_from: string
          effective_to?: string | null
          id?: string
          is_current?: boolean
          membership_type?: Database["public"]["Enums"]["party_membership_type"]
          office_title?: string | null
          party_id: string
          politician_id: string
          source_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Update: {
          created_at?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          is_current?: boolean
          membership_type?: Database["public"]["Enums"]["party_membership_type"]
          office_title?: string | null
          party_id?: string
          politician_id?: string
          source_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "party_memberships_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_memberships_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_house_members"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_position_holders"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "politicians"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "public_politician_overview"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "party_memberships_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      party_recognition_history: {
        Row: {
          created_at: string
          effective_from: string
          effective_to: string | null
          id: string
          order_reference: string | null
          party_id: string
          recognition_type: Database["public"]["Enums"]["recognition_type"]
          source_id: string | null
          state_id: string | null
          union_territory_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          effective_from: string
          effective_to?: string | null
          id?: string
          order_reference?: string | null
          party_id: string
          recognition_type: Database["public"]["Enums"]["recognition_type"]
          source_id?: string | null
          state_id?: string | null
          union_territory_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          effective_from?: string
          effective_to?: string | null
          id?: string
          order_reference?: string | null
          party_id?: string
          recognition_type?: Database["public"]["Enums"]["recognition_type"]
          source_id?: string | null
          state_id?: string | null
          union_territory_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "party_recognition_history_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_recognition_history_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
          {
            foreignKeyName: "party_recognition_history_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_recognition_history_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_recognition_history_union_territory_id_fkey"
            columns: ["union_territory_id"]
            isOneToOne: false
            referencedRelation: "union_territories"
            referencedColumns: ["id"]
          },
        ]
      }
      party_symbols: {
        Row: {
          created_at: string
          effective_from: string | null
          effective_to: string | null
          id: string
          image_url: string | null
          party_id: string
          symbol_name: string
          symbol_status: Database["public"]["Enums"]["symbol_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          effective_from?: string | null
          effective_to?: string | null
          id?: string
          image_url?: string | null
          party_id: string
          symbol_name: string
          symbol_status?: Database["public"]["Enums"]["symbol_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          effective_from?: string | null
          effective_to?: string | null
          id?: string
          image_url?: string | null
          party_id?: string
          symbol_name?: string
          symbol_status?: Database["public"]["Enums"]["symbol_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "party_symbols_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_symbols_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
        ]
      }
      person_aliases: {
        Row: {
          alias: string
          alias_type: Database["public"]["Enums"]["person_alias_type"]
          created_at: string
          id: string
          language: string | null
          person_id: string
        }
        Insert: {
          alias: string
          alias_type?: Database["public"]["Enums"]["person_alias_type"]
          created_at?: string
          id?: string
          language?: string | null
          person_id: string
        }
        Update: {
          alias?: string
          alias_type?: Database["public"]["Enums"]["person_alias_type"]
          created_at?: string
          id?: string
          language?: string | null
          person_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "person_aliases_person_id_fkey"
            columns: ["person_id"]
            isOneToOne: false
            referencedRelation: "persons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "person_aliases_person_id_fkey"
            columns: ["person_id"]
            isOneToOne: false
            referencedRelation: "public_politician_overview"
            referencedColumns: ["person_id"]
          },
        ]
      }
      persons: {
        Row: {
          bio: string | null
          created_at: string
          date_of_birth: string | null
          date_of_death: string | null
          education: string | null
          full_name: string
          gender: string | null
          id: string
          nationality: string
          occupation: string | null
          photo_url: string | null
          place_of_birth: string | null
          slug: string
          updated_at: string
        }
        Insert: {
          bio?: string | null
          created_at?: string
          date_of_birth?: string | null
          date_of_death?: string | null
          education?: string | null
          full_name: string
          gender?: string | null
          id?: string
          nationality?: string
          occupation?: string | null
          photo_url?: string | null
          place_of_birth?: string | null
          slug: string
          updated_at?: string
        }
        Update: {
          bio?: string | null
          created_at?: string
          date_of_birth?: string | null
          date_of_death?: string | null
          education?: string | null
          full_name?: string
          gender?: string | null
          id?: string
          nationality?: string
          occupation?: string | null
          photo_url?: string | null
          place_of_birth?: string | null
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      political_parties: {
        Row: {
          abbreviation: string | null
          created_at: string
          description: string | null
          founded_date: string | null
          headquarters_address: string | null
          id: string
          ideology: string[] | null
          logo_url: string | null
          name: string
          slug: string
          status: Database["public"]["Enums"]["party_status"]
          updated_at: string
          website: string | null
        }
        Insert: {
          abbreviation?: string | null
          created_at?: string
          description?: string | null
          founded_date?: string | null
          headquarters_address?: string | null
          id?: string
          ideology?: string[] | null
          logo_url?: string | null
          name: string
          slug: string
          status?: Database["public"]["Enums"]["party_status"]
          updated_at?: string
          website?: string | null
        }
        Update: {
          abbreviation?: string | null
          created_at?: string
          description?: string | null
          founded_date?: string | null
          headquarters_address?: string | null
          id?: string
          ideology?: string[] | null
          logo_url?: string | null
          name?: string
          slug?: string
          status?: Database["public"]["Enums"]["party_status"]
          updated_at?: string
          website?: string | null
        }
        Relationships: []
      }
      political_positions: {
        Row: {
          category: string
          created_at: string
          id: string
          level: string
          title: string
        }
        Insert: {
          category: string
          created_at?: string
          id?: string
          level: string
          title: string
        }
        Update: {
          category?: string
          created_at?: string
          id?: string
          level?: string
          title?: string
        }
        Relationships: []
      }
      politician_house_memberships: {
        Row: {
          constituency_id: string | null
          created_at: string
          end_date: string | null
          house_id: string
          id: string
          membership_type: Database["public"]["Enums"]["house_membership_type"]
          party_id: string | null
          politician_id: string
          source_id: string | null
          start_date: string
          state_id: string | null
          term_id: string | null
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        Insert: {
          constituency_id?: string | null
          created_at?: string
          end_date?: string | null
          house_id: string
          id?: string
          membership_type?: Database["public"]["Enums"]["house_membership_type"]
          party_id?: string | null
          politician_id: string
          source_id?: string | null
          start_date: string
          state_id?: string | null
          term_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Update: {
          constituency_id?: string | null
          created_at?: string
          end_date?: string | null
          house_id?: string
          id?: string
          membership_type?: Database["public"]["Enums"]["house_membership_type"]
          party_id?: string | null
          politician_id?: string
          source_id?: string | null
          start_date?: string
          state_id?: string | null
          term_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "politician_house_memberships_constituency_id_fkey"
            columns: ["constituency_id"]
            isOneToOne: false
            referencedRelation: "constituencies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_house_id_fkey"
            columns: ["house_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
          {
            foreignKeyName: "politician_house_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_house_members"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "politician_house_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "politician_house_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_position_holders"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "politician_house_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "politicians"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "public_politician_overview"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "politician_house_memberships_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_term_id_fkey"
            columns: ["term_id"]
            isOneToOne: false
            referencedRelation: "parliamentary_terms"
            referencedColumns: ["id"]
          },
        ]
      }
      politician_positions: {
        Row: {
          constituency_id: string | null
          created_at: string
          effective_from: string
          effective_to: string | null
          house_id: string | null
          id: string
          politician_id: string
          position_id: string
          source_id: string | null
          state_id: string | null
          title_override: string | null
          union_territory_id: string | null
          updated_at: string
          verification_status: Database["public"]["Enums"]["verification_status"]
        }
        Insert: {
          constituency_id?: string | null
          created_at?: string
          effective_from: string
          effective_to?: string | null
          house_id?: string | null
          id?: string
          politician_id: string
          position_id: string
          source_id?: string | null
          state_id?: string | null
          title_override?: string | null
          union_territory_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Update: {
          constituency_id?: string | null
          created_at?: string
          effective_from?: string
          effective_to?: string | null
          house_id?: string | null
          id?: string
          politician_id?: string
          position_id?: string
          source_id?: string | null
          state_id?: string | null
          title_override?: string | null
          union_territory_id?: string | null
          updated_at?: string
          verification_status?: Database["public"]["Enums"]["verification_status"]
        }
        Relationships: [
          {
            foreignKeyName: "politician_positions_constituency_id_fkey"
            columns: ["constituency_id"]
            isOneToOne: false
            referencedRelation: "constituencies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_house_id_fkey"
            columns: ["house_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_house_members"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "politician_positions_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "politician_positions_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_position_holders"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "politician_positions_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "politicians"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "public_politician_overview"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "politician_positions_position_id_fkey"
            columns: ["position_id"]
            isOneToOne: false
            referencedRelation: "current_position_holders"
            referencedColumns: ["position_id"]
          },
          {
            foreignKeyName: "politician_positions_position_id_fkey"
            columns: ["position_id"]
            isOneToOne: false
            referencedRelation: "political_positions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_union_territory_id_fkey"
            columns: ["union_territory_id"]
            isOneToOne: false
            referencedRelation: "union_territories"
            referencedColumns: ["id"]
          },
        ]
      }
      politicians: {
        Row: {
          created_at: string
          first_elected_year: number | null
          id: string
          official_website: string | null
          person_id: string
          status: Database["public"]["Enums"]["political_profile_status"]
          twitter_handle: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          first_elected_year?: number | null
          id?: string
          official_website?: string | null
          person_id: string
          status?: Database["public"]["Enums"]["political_profile_status"]
          twitter_handle?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          first_elected_year?: number | null
          id?: string
          official_website?: string | null
          person_id?: string
          status?: Database["public"]["Enums"]["political_profile_status"]
          twitter_handle?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "politicians_person_id_fkey"
            columns: ["person_id"]
            isOneToOne: true
            referencedRelation: "persons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politicians_person_id_fkey"
            columns: ["person_id"]
            isOneToOne: true
            referencedRelation: "public_politician_overview"
            referencedColumns: ["person_id"]
          },
        ]
      }
      portfolios: {
        Row: {
          created_at: string
          id: string
          ministry_id: string
          name: string
        }
        Insert: {
          created_at?: string
          id?: string
          ministry_id: string
          name: string
        }
        Update: {
          created_at?: string
          id?: string
          ministry_id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "portfolios_ministry_id_fkey"
            columns: ["ministry_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["ministry_id"]
          },
          {
            foreignKeyName: "portfolios_ministry_id_fkey"
            columns: ["ministry_id"]
            isOneToOne: false
            referencedRelation: "ministries"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string | null
          id: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
      source_records: {
        Row: {
          content_hash: string | null
          content_type: Database["public"]["Enums"]["source_content_type"]
          created_at: string
          fetched_at: string
          http_status: number | null
          id: string
          raw_content: string | null
          source_id: string
          storage_path: string | null
          url: string
        }
        Insert: {
          content_hash?: string | null
          content_type?: Database["public"]["Enums"]["source_content_type"]
          created_at?: string
          fetched_at?: string
          http_status?: number | null
          id?: string
          raw_content?: string | null
          source_id: string
          storage_path?: string | null
          url: string
        }
        Update: {
          content_hash?: string | null
          content_type?: Database["public"]["Enums"]["source_content_type"]
          created_at?: string
          fetched_at?: string
          http_status?: number | null
          id?: string
          raw_content?: string | null
          source_id?: string
          storage_path?: string | null
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "source_records_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          },
        ]
      }
      sources: {
        Row: {
          authority_rank: number
          base_url: string | null
          created_at: string
          id: string
          is_active: boolean
          name: string
          organization: string | null
          source_type: Database["public"]["Enums"]["source_type"]
          updated_at: string
        }
        Insert: {
          authority_rank?: number
          base_url?: string | null
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          organization?: string | null
          source_type: Database["public"]["Enums"]["source_type"]
          updated_at?: string
        }
        Update: {
          authority_rank?: number
          base_url?: string | null
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          organization?: string | null
          source_type?: Database["public"]["Enums"]["source_type"]
          updated_at?: string
        }
        Relationships: []
      }
      states: {
        Row: {
          area_sq_km: number | null
          capital: string | null
          code: string | null
          created_at: string
          formation_date: string | null
          id: string
          name: string
          official_languages: string[] | null
          population: number | null
          slug: string
          status: Database["public"]["Enums"]["geography_status"]
          updated_at: string
        }
        Insert: {
          area_sq_km?: number | null
          capital?: string | null
          code?: string | null
          created_at?: string
          formation_date?: string | null
          id?: string
          name: string
          official_languages?: string[] | null
          population?: number | null
          slug: string
          status?: Database["public"]["Enums"]["geography_status"]
          updated_at?: string
        }
        Update: {
          area_sq_km?: number | null
          capital?: string | null
          code?: string | null
          created_at?: string
          formation_date?: string | null
          id?: string
          name?: string
          official_languages?: string[] | null
          population?: number | null
          slug?: string
          status?: Database["public"]["Enums"]["geography_status"]
          updated_at?: string
        }
        Relationships: []
      }
      union_territories: {
        Row: {
          area_sq_km: number | null
          capital: string | null
          code: string | null
          created_at: string
          formation_date: string | null
          has_legislature: boolean
          id: string
          name: string
          population: number | null
          slug: string
          status: Database["public"]["Enums"]["geography_status"]
          updated_at: string
        }
        Insert: {
          area_sq_km?: number | null
          capital?: string | null
          code?: string | null
          created_at?: string
          formation_date?: string | null
          has_legislature?: boolean
          id?: string
          name: string
          population?: number | null
          slug: string
          status?: Database["public"]["Enums"]["geography_status"]
          updated_at?: string
        }
        Update: {
          area_sq_km?: number | null
          capital?: string | null
          code?: string | null
          created_at?: string
          formation_date?: string | null
          has_legislature?: boolean
          id?: string
          name?: string
          population?: number | null
          slug?: string
          status?: Database["public"]["Enums"]["geography_status"]
          updated_at?: string
        }
        Relationships: []
      }
      user_admin_roles: {
        Row: {
          admin_role_id: string
          granted_at: string
          granted_by: string | null
          id: string
          user_id: string
        }
        Insert: {
          admin_role_id: string
          granted_at?: string
          granted_by?: string | null
          id?: string
          user_id: string
        }
        Update: {
          admin_role_id?: string
          granted_at?: string
          granted_by?: string | null
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_admin_roles_admin_role_id_fkey"
            columns: ["admin_role_id"]
            isOneToOne: false
            referencedRelation: "admin_roles"
            referencedColumns: ["id"]
          },
        ]
      }
      verification_records: {
        Row: {
          created_at: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          field_name: string | null
          id: string
          notes: string | null
          status: Database["public"]["Enums"]["verification_status"]
          updated_at: string
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          created_at?: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          field_name?: string | null
          id?: string
          notes?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          created_at?: string
          entity_id?: string
          entity_type?: Database["public"]["Enums"]["entity_type"]
          field_name?: string | null
          id?: string
          notes?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      current_house_members: {
        Row: {
          constituency_id: string | null
          constituency_name: string | null
          constituency_slug: string | null
          full_name: string | null
          house_id: string | null
          house_membership_id: string | null
          house_name: string | null
          house_type: Database["public"]["Enums"]["house_type"] | null
          membership_type:
            | Database["public"]["Enums"]["house_membership_type"]
            | null
          party_abbreviation: string | null
          party_id: string | null
          party_name: string | null
          person_slug: string | null
          photo_url: string | null
          politician_id: string | null
          start_date: string | null
          state_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "politician_house_memberships_constituency_id_fkey"
            columns: ["constituency_id"]
            isOneToOne: false
            referencedRelation: "constituencies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_house_id_fkey"
            columns: ["house_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_house_memberships_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
          {
            foreignKeyName: "politician_house_memberships_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
        ]
      }
      current_ministers: {
        Row: {
          effective_from: string | null
          full_name: string | null
          government_id: string | null
          is_primary: boolean | null
          minister_assignment_id: string | null
          ministry_id: string | null
          ministry_name: string | null
          person_slug: string | null
          photo_url: string | null
          politician_id: string | null
          portfolio_id: string | null
          portfolio_name: string | null
          rank: Database["public"]["Enums"]["minister_rank"] | null
        }
        Relationships: [
          {
            foreignKeyName: "minister_assignments_government_id_fkey"
            columns: ["government_id"]
            isOneToOne: false
            referencedRelation: "governments"
            referencedColumns: ["id"]
          },
        ]
      }
      current_party_memberships: {
        Row: {
          effective_from: string | null
          membership_type:
            | Database["public"]["Enums"]["party_membership_type"]
            | null
          office_title: string | null
          party_abbreviation: string | null
          party_id: string | null
          party_membership_id: string | null
          party_name: string | null
          politician_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "party_memberships_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_memberships_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_house_members"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_ministers"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "current_position_holders"
            referencedColumns: ["politician_id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "politicians"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_memberships_politician_id_fkey"
            columns: ["politician_id"]
            isOneToOne: false
            referencedRelation: "public_politician_overview"
            referencedColumns: ["politician_id"]
          },
        ]
      }
      current_position_holders: {
        Row: {
          constituency_id: string | null
          effective_from: string | null
          full_name: string | null
          house_id: string | null
          person_slug: string | null
          photo_url: string | null
          politician_id: string | null
          politician_position_id: string | null
          position_category: string | null
          position_id: string | null
          position_level: string | null
          position_title: string | null
          state_id: string | null
          union_territory_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "politician_positions_constituency_id_fkey"
            columns: ["constituency_id"]
            isOneToOne: false
            referencedRelation: "constituencies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_house_id_fkey"
            columns: ["house_id"]
            isOneToOne: false
            referencedRelation: "houses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "politician_positions_union_territory_id_fkey"
            columns: ["union_territory_id"]
            isOneToOne: false
            referencedRelation: "union_territories"
            referencedColumns: ["id"]
          },
        ]
      }
      party_election_results: {
        Row: {
          candidates_contested: number | null
          election_id: string | null
          election_name: string | null
          party_abbreviation: string | null
          party_id: string | null
          party_name: string | null
          seats_won: number | null
          total_votes: number | null
        }
        Relationships: [
          {
            foreignKeyName: "election_candidates_election_id_fkey"
            columns: ["election_id"]
            isOneToOne: false
            referencedRelation: "elections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "election_candidates_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "election_candidates_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
        ]
      }
      public_party_overview: {
        Row: {
          abbreviation: string | null
          current_president_name: string | null
          current_recognition_type:
            | Database["public"]["Enums"]["recognition_type"]
            | null
          founded_date: string | null
          logo_url: string | null
          name: string | null
          party_id: string | null
          slug: string | null
          status: Database["public"]["Enums"]["party_status"] | null
        }
        Relationships: []
      }
      public_politician_overview: {
        Row: {
          current_constituency_name: string | null
          current_constituency_slug: string | null
          current_house_name: string | null
          current_house_type: Database["public"]["Enums"]["house_type"] | null
          current_party_abbreviation: string | null
          current_party_id: string | null
          current_party_name: string | null
          current_position_title: string | null
          full_name: string | null
          person_id: string | null
          photo_url: string | null
          politician_id: string | null
          slug: string | null
          status: Database["public"]["Enums"]["political_profile_status"] | null
        }
        Relationships: [
          {
            foreignKeyName: "party_memberships_party_id_fkey"
            columns: ["current_party_id"]
            isOneToOne: false
            referencedRelation: "political_parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_memberships_party_id_fkey"
            columns: ["current_party_id"]
            isOneToOne: false
            referencedRelation: "public_party_overview"
            referencedColumns: ["party_id"]
          },
        ]
      }
    }
    Functions: {
      get_current_government: {
        Args: { p_state_id?: string }
        Returns: {
          formed_date: string
          government_id: string
          level: Database["public"]["Enums"]["government_level"]
          term_number: number
        }[]
      }
      get_current_party: {
        Args: { p_politician_id: string }
        Returns: {
          effective_from: string
          party_abbreviation: string
          party_id: string
          party_name: string
        }[]
      }
      get_current_positions: {
        Args: { p_politician_id: string }
        Returns: {
          category: string
          constituency_id: string
          effective_from: string
          house_id: string
          level: string
          position_id: string
          state_id: string
          title: string
        }[]
      }
      has_admin_role: {
        Args: { required_role: Database["public"]["Enums"]["admin_role_name"] }
        Returns: boolean
      }
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean }
      search_entities: {
        Args: { result_limit?: number; search_query: string }
        Returns: Database["public"]["CompositeTypes"]["search_result"][]
      }
    }
    Enums: {
      admin_role_name:
        | "SUPER_ADMIN"
        | "DATA_ADMIN"
        | "DATA_REVIEWER"
        | "EDITOR"
        | "READ_ONLY"
      audit_action:
        | "CREATE"
        | "UPDATE"
        | "DELETE"
        | "VERIFY"
        | "REJECT"
        | "IMPORT"
        | "PUBLISH"
        | "ARCHIVE"
        | "RESTORE"
      candidate_nomination_status:
        | "NOMINATED"
        | "ACCEPTED"
        | "REJECTED"
        | "WITHDRAWN"
        | "CONTESTED"
      candidate_result_status:
        | "ELECTED"
        | "RUNNER_UP"
        | "LOST"
        | "WITHDRAWN"
        | "DISQUALIFIED"
      constituency_type: "LOK_SABHA" | "ASSEMBLY"
      correction_status:
        | "PENDING"
        | "UNDER_REVIEW"
        | "ACCEPTED"
        | "REJECTED"
        | "DUPLICATE"
      data_quality_issue_type:
        | "MISSING_SOURCE"
        | "DUPLICATE"
        | "INVALID_DATE"
        | "INVALID_RELATIONSHIP"
        | "STALE_RECORD"
        | "CONFLICTING_SOURCE"
        | "MISSING_REQUIRED_FIELD"
        | "PARSER_ERROR"
        | "OTHER"
      data_quality_severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
      deposit_status: "SAVED" | "FORFEITED"
      document_type:
        | "PARTY_CONSTITUTION"
        | "ECI_ORDER"
        | "ELECTION_RESULT"
        | "AFFIDAVIT"
        | "EXPENDITURE_REPORT"
        | "CONTRIBUTION_REPORT"
        | "GOVERNMENT_DOCUMENT"
        | "PARLIAMENT_DOCUMENT"
        | "OTHER"
      election_status: "UPCOMING" | "ONGOING" | "COMPLETED" | "CANCELLED"
      election_type:
        | "LOK_SABHA"
        | "ASSEMBLY"
        | "RAJYA_SABHA"
        | "PRESIDENTIAL"
        | "VICE_PRESIDENTIAL"
        | "BY_ELECTION"
        | "OTHER"
      entity_source_relationship:
        | "PRIMARY_SOURCE"
        | "SUPPORTING_SOURCE"
        | "HISTORICAL_SOURCE"
        | "DOCUMENT_SOURCE"
        | "IMAGE_SOURCE"
      entity_type:
        | "PERSON"
        | "POLITICIAN"
        | "POLITICAL_PARTY"
        | "CONSTITUENCY"
        | "ELECTION"
        | "ELECTION_CANDIDATE"
        | "GOVERNMENT"
        | "MINISTRY"
        | "STATE"
        | "UNION_TERRITORY"
        | "DISTRICT"
        | "HOUSE"
      geography_status: "ACTIVE" | "INACTIVE" | "HISTORICAL"
      government_level: "UNION" | "STATE" | "UNION_TERRITORY"
      government_party_role:
        | "LEAD_PARTY"
        | "COALITION_PARTNER"
        | "SUPPORTING_PARTY"
        | "OTHER"
      government_status: "CURRENT" | "FORMER"
      house_membership_type: "ELECTED" | "NOMINATED" | "BY_ELECTION"
      house_type:
        | "LOK_SABHA"
        | "RAJYA_SABHA"
        | "STATE_LEGISLATIVE_ASSEMBLY"
        | "STATE_LEGISLATIVE_COUNCIL"
      import_match_status:
        | "NEW"
        | "MATCHED"
        | "POTENTIAL_DUPLICATE"
        | "UNMATCHED"
        | "REJECTED"
      import_status:
        | "PENDING"
        | "RUNNING"
        | "COMPLETED"
        | "PARTIAL"
        | "FAILED"
        | "CANCELLED"
      minister_rank: "CABINET" | "INDEPENDENT_CHARGE" | "STATE_MINISTER"
      party_alias_type:
        | "ABBREVIATION"
        | "TRANSLITERATION"
        | "LOCAL_LANGUAGE"
        | "FORMER_NAME"
        | "OTHER"
      party_membership_type:
        | "MEMBER"
        | "OFFICE_BEARER"
        | "FOUNDER"
        | "LEADER"
        | "OTHER"
      party_status: "ACTIVE" | "DISSOLVED" | "MERGED" | "INACTIVE"
      person_alias_type:
        | "COMMON_NAME"
        | "INITIALS"
        | "TRANSLITERATION"
        | "LOCAL_LANGUAGE"
        | "FORMER_NAME"
        | "OTHER"
      political_profile_status: "ACTIVE" | "FORMER" | "DECEASED" | "INACTIVE"
      recognition_type: "NATIONAL" | "STATE" | "REGISTERED_UNRECOGNISED"
      reservation_category: "GENERAL" | "SC" | "ST"
      source_content_type:
        | "HTML"
        | "PDF"
        | "JSON"
        | "CSV"
        | "XML"
        | "IMAGE"
        | "OTHER"
      source_type:
        | "ECI"
        | "PARLIAMENT"
        | "CENTRAL_GOVERNMENT"
        | "STATE_GOVERNMENT"
        | "UT_GOVERNMENT"
        | "POLITICAL_PARTY"
        | "LEGISLATIVE_BODY"
        | "OFFICIAL_PERSONAL"
        | "SECONDARY"
        | "USER_SUBMITTED"
        | "OTHER"
      symbol_status: "RESERVED" | "FREE" | "HISTORICAL"
      verification_status:
        | "UNVERIFIED"
        | "PENDING_REVIEW"
        | "VERIFIED"
        | "REJECTED"
        | "STALE"
    }
    CompositeTypes: {
      search_result: {
        entity_type: string | null
        entity_id: string | null
        title: string | null
        subtitle: string | null
        slug: string | null
        rank: number | null
      }
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals["public"]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never
